[package]
name = "bsfs_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiarray = "0.1.3"
rstest = "0.19.0"
itertools = "0.12.1"
ndarray = "0.15.6"